Add standard metrics getters
sd2k/rocket_prometheus pull request #19
Opened 2022-06-22 11:56 UTC by IvashchenkoSerhii

Add `PrometheusMetrics::http_requests_total` and `PrometheusMetrics::http_requests_duration_seconds` methods to get a reference to the fairing's internal Prometheus metrics. For ability to custom initialize of these metrics, which required for correct handling of Counters resets.

Example:

```rust
    let base_statuses = vec!["200"];
    let api_statuses = vec!["200", "400", "401"];

    for route in rocket.routes() {
        let uri = route.uri.as_str();
        let method = route.method.as_str();
        let statuses = match uri {
            v if v.contains("api") => &api_statuses,
            _ => &base_statuses,
        };
        for status in statuses {
            prometheus
                .http_requests_total()
                .with_label_values(&[uri, method, status]);

            prometheus
                .http_requests_duration_seconds()
                .with_label_values(&[uri, method, status]);
        }
    }
```

2022-06-22 20:16 UTC, sd2k requested changes
Thanks for the contribution! I've made a few suggestions inline mostly for docs changes but also to remove the `get_` prefix from the methods following the [Rust API guidelines](https://rust-lang.github.io/api-guidelines/naming.html#getter-names-follow-rust-convention-c-getter).

Just out of interest, why do you need to access the internal metrics?

2022-06-22 20:16 UTC, sd2k commented on src/lib.rs
> +    pub fn get_http_requests_duration_seconds(&self) -> &HistogramVec {
```suggestion
    pub fn http_requests_duration_seconds(&self) -> &HistogramVec {
```

2022-06-22 20:16 UTC, sd2k commented on src/lib.rs
> +    pub fn get_http_requests_total(&self) -> &IntCounterVec {
```suggestion
    pub fn http_requests_total(&self) -> &IntCounterVec {
```

2022-06-22 20:16 UTC, sd2k commented on src/lib.rs
> +    pub fn get_http_requests_total(&self) -> &IntCounterVec {
```suggestion
    pub fn http_requests_total(&self) -> &IntCounterVec {
```

2022-06-22 20:16 UTC, sd2k commented on CHANGELOG.md
> +- Add `PrometheusMetrics::get_http_requests_total` function.
```suggestion
- Add `PrometheusMetrics::http_requests_total` and `PrometheusMetrics::http_requests_duration_seconds` methods to get a reference to the fairing's internal Prometheus metrics. 
```

2022-06-22 20:16 UTC, sd2k commented on CHANGELOG.md
> +- Add `PrometheusMetrics::get_http_requests_duration_seconds` function.
```suggestion
```

2022-06-22 20:16 UTC, sd2k commented on src/lib.rs
> +    /// Get `http_requests_duration_seconds` metric.
```suggestion
    /// Get the `http_requests_duration_seconds` metric.
```

2022-06-22 20:16 UTC, sd2k commented on src/lib.rs
> +    /// Get `http_requests_total` metric.
```suggestion
    /// Get the `http_requests_total` metric.
```

2022-06-22 21:21 UTC, IvashchenkoSerhii commented on src/lib.rs
> +    pub fn get_http_requests_total(&self) -> &IntCounterVec {
Thanks for suggestions and guideline!

> why do you need to access the internal metrics?

Prometheus [rate](https://prometheus.io/docs/prometheus/latest/querying/functions/#rate)-like functions can automatically adjust `Counter` metric restarts if that metric initialized with `0` on startup: `some_value -> 0 -> 1`. But if counter do not initialize by 0, we have states: `some_value -> unknown -> 1` and `rate` function skip this `unknown -> 1` step and continues calculations from `1 -> 2`.  Initialization of the internal metrics fixes that problem. Some doc suggestion: https://prometheus.io/docs/practices/instrumentation/#avoid-missing-metrics.

2022-06-23 08:01 UTC, sd2k commented on src/lib.rs
> +    pub fn get_http_requests_total(&self) -> &IntCounterVec {
Huh, interesting, I didn't know that. I've played around with some of my Go services which use the `promauto` Go package and they don't seem to do that 🤷 I wonder what happens if Prometheus doesn't scrape the service until after the service has incremented the counters N>1 times after a restart, too -- how does Prometheus recognise it as a restart?

Anyway, I'm happy to merge this in, thanks again for the contribution 😄

2022-06-23 08:05 UTC, merged

2022-06-23 08:19 UTC, sd2k commented
This has been released to crates.io in v0.10.0-rc.3 👍

2022-06-23 08:43 UTC, IvashchenkoSerhii commented on src/lib.rs
> +    pub fn get_http_requests_total(&self) -> &IntCounterVec {
I set a time range with server restart and got:

Query: `histogram_quantile(0.99, sum(rate(rocket_http_requests_duration_seconds_bucket{endpoint="/some-endpoint"", method="POST"}[$__rate_interval])) by (le))`

![image](https://user-images.githubusercontent.com/26857105/175254912-86996ee9-7a4a-4596-96f5-295f3738d53a.png)

But custom initialized metric in the same time range works:

`histogram_quantile(0.99, sum(rate(rocket_some_custom_initialized_bucket{field="some_value"}[$__rate_interval])) by (field,le)) `
![image](https://user-images.githubusercontent.com/26857105/175254520-c9934fb7-1d2a-4978-a040-3ee592e817fb.png)